---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-identifier
  namespace: default
  labels:
    app: cloud-identifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-identifier
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-identifier
    spec:
      containers:
      - image: tonylee1993/hack-container:latest
        imagePullPolicy: Always
        name: cloud-identifier
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-identifier
  namespace: default
  labels:
    app: cloud-identifier
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hack-container
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-identifier-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: cloud-identifier
          servicePort: 8080
