---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memegrabber
  namespace: default
  labels:
    app: memegrabber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memegrabber
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memegrabber
    spec:
      containers:
      - image: nwang92/memegrabber:latest
        imagePullPolicy: Always
        name: memegrabber
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: memegrabber
  namespace: default
  labels:
    app: memegrabber
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: memegrabber
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: memegrabber-ingress
  namespace: default
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/tls.md#server-side-https-enforcement-through-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/app-root: /memegrabber
spec:
  rules:
  - http:
      paths:
      - path: /memegrabber
        backend:
          serviceName: memegrabber
          servicePort: 8000
