---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  namespace: default
  labels:
    app: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - image: splunk/splunk:latest
        imagePullPolicy: Always
        name: splunk
        ports:
        - containerPort: 8000
        env:
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_PASSWORD
          value: Chang3d!
        - name: SPLUNK_ROOT_ENDPOINT
          value: /splunk
---
apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: default
  labels:
    app: splunk
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: splunk
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: splunk-ingress
  namespace: default
  # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/tls.md#server-side-https-enforcement-through-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  - http:
      paths:
      - path: /splunk
        backend:
          serviceName: splunk
          servicePort: 8000
